# Generated by Django 2.2.1 on 2019-05-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expertises',
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.UserExpertise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_answers', to='main.Answer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(null=True, related_name='user_bids', to='main.Bids'),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserLanguage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.UserLocation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='multilingual',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_questions', to='main.Question'),
        ),
    ]
