# Generated by Django 2.2.1 on 2019-05-11 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190511_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='flags',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_flags', to='main.AnswerFlags'),
        ),
        migrations.AlterField(
            model_name='answerflags',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Answer'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='rating_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.RatingType'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Question'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='flags',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_flags', to='main.QuestionFlags'),
        ),
        migrations.AlterField(
            model_name='questionflags',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(related_name='user_bids', to='main.Bids'),
        ),
        migrations.AlterField(
            model_name='userexpertise',
            name='dewey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Dewey'),
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('location', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='logins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_logins', to='main.UserLogin'),
            preserve_default=False,
        ),
    ]
