# Generated by Django 2.2.1 on 2019-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190511_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dewey',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
