# Generated by Django 2.2.1 on 2019-05-15 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190515_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='dewey',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dewey_children', to='main.Dewey'),
        ),
        migrations.AddField(
            model_name='dewey',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dewey_parents', to='main.Dewey'),
        ),
    ]
