# Generated by Django 2.2.1 on 2019-05-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190515_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(null=True, related_name='user_bids', to='main.Bids'),
        ),
    ]
