# Generated by Django 2.2.1 on 2019-05-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190515_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(related_name='user_bids', to='main.Bids'),
        ),
    ]
