# Generated by Django 2.2.1 on 2019-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190515_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('wPW', 'wrong password'), ('wEC', 'wrong email confirmation code'), ('wPC', 'wrong phone confirmation code'), ('cPI', 'change of payment info'), ('cPN', 'change of phone number'), ('cAD', 'change of address'), ('rPR', 'request of password reset'), ('rPC', 'request of password change')], max_length=3)),
                ('detail', models.CharField(max_length=64, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('location', models.TextField()),
            ],
        ),
    ]
