# Generated by Django 2.2.1 on 2019-05-17 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event',
            field=models.CharField(choices=[('cEM', 'cEM'), ('cPN', 'cPN'), ('wPW', 'wrong password'), ('wEC', 'wrong email confirmation code'), ('wPC', 'wrong phone confirmation code'), ('cPI', 'change of payment info'), ('cPN', 'change of phone number'), ('cAD', 'change of address'), ('rPR', 'request of password reset'), ('rPC', 'request of password change')], max_length=3),
        ),
    ]
