# Generated by Django 2.2.1 on 2019-05-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190517_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
